export default {
  space: 2,
  semicolon: false,
  prettier: false,
  ignores: ['xo.config.js'],
  rules: {
    'react/react-in-jsx-scope': 'off',
    'react/prop-types': 'off',
    '@typescript-eslint/naming-convention': 'off',
    'unicorn/filename-case': 'off',
    'import/extensions': 'off',
    'import-x/extensions': 'off',
    'n/file-extension-in-import': 'off',
    '@typescript-eslint/triple-slash-reference': 'off',
    'react/function-component-definition': 'off',
    'unicorn/prevent-abbreviations': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/strict-boolean-expressions': 'off',
    '@typescript-eslint/no-unsafe-assignment': 'off',
    '@typescript-eslint/no-unsafe-argument': 'off',
    '@typescript-eslint/no-floating-promises': 'off',
    'no-alert': 'off',
    'new-cap': 'off',
    '@typescript-eslint/prefer-nullish-coalescing': 'off',
    'n/prefer-global/buffer': 'off',
    'n/prefer-global/process': 'off',
    '@stylistic/max-len': 'off',
  },
}
